# Reusable Workflow: Build Antora Documentation Site
# This workflow can be called from other workflows to build the Antora site.

name: Build Antora Site

on:
  workflow_call: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout playbook source
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install Antora and Dependencies
        run: npm install

      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@d2bee4f07e8ca410d6b196d00f90c12e7d48c33a # v2.6.0
        with:
          compose-file: './compose.yml'

      - name: Generate Site
        run: npm run build

      - name: Upload built site
        uses: actions/upload-artifact@v7
        with:
          name: antora-site
          path: build/site
          retention-days: 1
